import { RESPONSE_MESSAGES } from "../constants/responseMessage.constants.js";
import { Buckets } from "../model/bucket.model.js";
import QRCode from "qrcode";
import { sendEmail } from "../utils/sendMail.js";

class BucketService {
    async createBucket(body, userId) {
        const bucket = await Buckets.create({
            ...body,
            user: userId,
        });

        return bucket;
    }

    async getBuckets() {
        const buckets = await Buckets.find().populate(
            "photographer",
            "name email"
        );
        return buckets;
    }

    async getBucket(id) {
        const bucket = await Buckets.findById(id).populate(
            "photographer",
            "name email"
        );

        if (!bucket) {
            throw new Error("Bucket not found");
        }

        return bucket;
    }

    async updateBucket(id, body, userId) {
        const bucket = await Buckets.findById(id);

        if (!bucket) {
            throw new Error("Bucket not found");
        }

        if (bucket.photographer.toString() !== userId) {
            throw new Error("Not authorized to update this bucket");
        }

        const updatedBucket = await Buckets.findByIdAndUpdate(id, body, {
            new: true,
            runValidators: true,
        });

        return updatedBucket;
    }

    async deleteBucket(id, userId) {
        const bucket = await Buckets.findById(id);

        if (!bucket) {
            throw new Error("Bucket not found");
        }

        if (bucket.photographer.toString() !== userId) {
            throw new Error("Not authorized to delete this bucket");
        }

        await bucket.deleteOne();
        return { message: "Bucket deleted successfully" };
    }

    async generateQRCode(id, userId) {
        const bucket = await Buckets.findById(id).populate(
            "photographer",
            "name email"
        );

        if (!bucket) {
            throw new Error("Bucket not found");
        }

        if (bucket.photographer.toString() !== userId) {
            throw new Error(
                "Not authorized to generate QR code for this bucket"
            );
        }

        // Generate QR code data URL
        const qrCodeDataUrl = await QRCode.toDataURL(
            JSON.stringify({
                bucketId: bucket._id,
                bucketName: bucket.name,
                studioId: bucket.studio,
                photographerId: bucket.photographer._id,
                photographerName: bucket.photographer.name,
                timestamp: new Date().toISOString(),
            })
        );

        return {
            qrCode: qrCodeDataUrl,
            bucket,
        };
    }

    async sendQRCode(id, email, userId) {
        const bucket = await Buckets.findById(id).populate(
            "photographer",
            "name email"
        );

        if (!bucket) {
            throw new Error("Bucket not found");
        }

        if (bucket.photographer.toString() !== userId) {
            throw new Error("Not authorized to send QR code for this bucket");
        }

        // Generate QR code
        const { qrCode } = await this.generateQRCode(id, userId);

        // Send email with QR code
        await sendEmail({
            to: email,
            subject: `QR Code for ${bucket.name}`,
            html: `
                <h1>QR Code for ${bucket.name}</h1>
                <p>Here is the QR code for accessing the bucket "${bucket.name}".</p>
                <p>This QR code was generated by ${bucket.photographer.name}.</p>
                <img src="${qrCode}" alt="Bucket QR Code" />
                <p>Scan this QR code to access the bucket.</p>
            `,
        });

        return {
            message: "QR code sent successfully",
            bucket,
        };
    }

    async requestBucketAccess(id, userId) {
        const bucket = await Buckets.findById(id).populate(
            "photographer",
            "name email"
        );

        if (!bucket) {
            throw new Error("Bucket not found");
        }

        // Check if user is not the bucket owner
        if (bucket.photographer.toString() === userId) {
            throw new Error("Cannot request access to your own bucket");
        }

        // Check if user already has access
        if (
            bucket.accessList.some(
                (access) => access.user.toString() === userId
            )
        ) {
            throw new Error("You already have access to this bucket");
        }

        // Check if user already has a pending request
        if (
            bucket.accessRequests.some(
                (request) => request.user.toString() === userId
            )
        ) {
            throw new Error("You already have a pending access request");
        }

        // Add access request
        bucket.accessRequests.push({
            user: userId,
            status: "pending",
            requestedAt: new Date(),
        });

        await bucket.save();

        // Send notification email to photographer
        await sendEmail({
            to: bucket.photographer.email,
            subject: "New Bucket Access Request",
            html: `
                <h1>New Access Request</h1>
                <p>Someone has requested access to your bucket "${bucket.name}".</p>
                <p>Please review and respond to this request.</p>
            `,
        });

        return bucket;
    }

    async respondToAccessRequest(id, requestId, response, userId) {
        const bucket = await Buckets.findById(id).populate(
            "photographer",
            "name email"
        );

        if (!bucket) {
            throw new Error("Bucket not found");
        }

        // Check if user is the bucket owner
        if (bucket.photographer.toString() !== userId) {
            throw new Error("Not authorized to respond to access requests");
        }

        // Find the access request
        const accessRequest = bucket.accessRequests.id(requestId);
        if (!accessRequest) {
            throw new Error("Access request not found");
        }

        if (response === "accept") {
            // Add user to access list
            bucket.accessList.push({
                user: accessRequest.user,
                role: "viewer",
                grantedAt: new Date(),
            });

            // Send acceptance email to user
            await sendEmail({
                to: accessRequest.user.email,
                subject: "Bucket Access Request Accepted",
                html: `
                    <h1>Access Request Accepted</h1>
                    <p>Your request for access to "${bucket.name}" has been accepted.</p>
                    <p>You can now view the contents of this bucket.</p>
                `,
            });
        } else if (response === "reject") {
            // Send rejection email to user
            await sendEmail({
                to: accessRequest.user.email,
                subject: "Bucket Access Request Rejected",
                html: `
                    <h1>Access Request Rejected</h1>
                    <p>Your request for access to "${bucket.name}" has been rejected.</p>
                `,
            });
        } else {
            throw new Error(
                "Invalid response. Must be either 'accept' or 'reject'"
            );
        }

        // Remove the access request
        bucket.accessRequests = bucket.accessRequests.filter(
            (request) => request._id.toString() !== requestId
        );

        await bucket.save();

        return {
            message: `Access request ${response}ed successfully`,
            bucket,
        };
    }
}

export default new BucketService();
